export const teamMembers = [
  {
    id: "1",
    name: "Basia Sołtysińska",
    position: "Founder",
    city: "Warsaw",
    email: "mateusz.cierpisz@gmail.com",
    image: "https://source.unsplash.com/random/180x180",
  },
  {
    id: "2",
    name: "Włas Chorowiec",
    position: "Founder",
    city: "Warsaw",
    email: "mateusz.cierpisz@gmail.com",
    image: "https://source.unsplash.com/random/180x180",
  },
  {
    id: "3",
    name: "Edyta Leśniewska",
    position: "Head of Human Resources",
    city: "Warsaw",
    email: "mateusz.cierpisz@gmail.com",
    image: "https://source.unsplash.com/random/180x180",
  },
  {
    id: "4",
    name: "Joanna Pawluk",
    position: "Chief Growth Officer (CGO)",
    city: "London",
    email: "mateusz.cierpisz@gmail.com",
    image: "https://source.unsplash.com/random/180x180",
  },
  {
    id: "5",
    name: "David Saunders",
    position: "Business Development",
    city: "London",
    email: "mateusz.cierpisz@gmail.com",
    image: "https://source.unsplash.com/random/180x180",
  },
  {
    id: "6",
    name: "Adam Eldridge",
    position: "Business Development Director US",
    city: "Los Angeles",
    email: "mateusz.cierpisz@gmail.com",
    image: "https://source.unsplash.com/random/180x180",
  },
  {
    id: "7",
    name: "Maha Mahda",
    position: "Chief Business Development Officer (CBDO)",
    city: "Warsaw",
    email: "mateusz.cierpisz@gmail.com",
    image: "https://source.unsplash.com/random/180x180",
  },
  {
    id: "8",
    name: "Elżbieta Kamińska",
    position: "International Client Service Manager",
    city: "Warsaw",
    email: "mateusz.cierpisz@gmail.com",
    image: "https://source.unsplash.com/random/180x180",
  },
  {
    id: "9",
    name: "Karolina Makuch",
    position: "Creation Manager",
    city: "Warsaw",
    email: "mateusz.cierpisz@gmail.com",
    image: "https://source.unsplash.com/random/180x180",
  },
  {
    id: "10",
    name: "Kamil Bolek",
    position: "Head of Communication",
    city: "Warsaw",
    email: "mateusz.cierpisz@gmail.com",
    image: "https://source.unsplash.com/random/180x180",
  },
];
